### ISSUE TITLE
Room ID in POST MESSAGE

### ISSUE THREAD

**Issue by freescout-helpdesk** [alekseykuleshov/rocket-chat#12]
Can Channel ID be passed to https://github.com/alekseykuleshov/rocket-chat/tree/master/src/Messages#post-message as ROOM ID?

**Comment by alekseykuleshov** [comment]
@freescout-helpdesk Yes, ROOM ID can be either Channel ID or Group ID, that should work.

**Comment by freescout-helpdesk** [comment]
Thanks
