### ISSUE TITLE
Pb with roomId or NameId in group or user

### ISSUE THREAD

**Issue by viduc** [alekseykuleshov/rocket-chat#14]
Hello!
Thanks for your plugin !!

i have a pb if i try to use info or other method when we must send roomId or roomName...

i try to do this:
```
$group = new \ATDev\RocketChat\Groups\Group();
            $group->setName('DGDSI');
            $group->info();
```
and i obtain that:
![Sélection_081](https://user-images.githubusercontent.com/5895566/156600549-d9885db0-ded5-44bc-bee6-dcb9df8f0772.png)

i try to do this too:
`$group = new \ATDev\RocketChat\Groups\Group(['roomName' => 'GDGSI']);`

can you give me some example how use this request ?

Thanks!

**Comment by alekseykuleshov** [comment]
@viduc Currently it's possible to get group info by id only. I'll do an update on a weekend to make it work with the group name too.

**Comment by viduc** [comment]
Thanks,

i try to send with roomId too but i have the same result...
Did we must be loggin with the owner of group ? I use admin account to do that.

**Comment by alekseykuleshov** [comment]
@viduc Check this code, it works for me.

```
$group = new \ATDev\RocketChat\Groups\Group();
$group->setName("TEST1234");
$group->create();

var_dump($group);

$group2 = new \ATDev\RocketChat\Groups\Group();
$group2->setGroupId($group->getGroupId());
$group2Copy = $group2->info();

var_dump($group2);
var_dump($group2Copy);
```

Admin account sees everything.

**Comment by viduc** [comment]
Hi, thanks for your help.

I try to do that:
![Sélection_083](https://user-images.githubusercontent.com/5895566/157196818-f1448fe3-0b7d-4bd8-810f-28ef13434b92.png)

but i have same result:
![Sélection_084](https://user-images.githubusercontent.com/5895566/157196946-90b39fd1-70d3-4b06-a55b-40a4a97de18c.png)

**Comment by alekseykuleshov** [comment]
@viduc It's stated that you have to be a member of the group to use `info()` method: https://developer.rocket.chat/reference/api/rest-api/endpoints/team-collaboration-endpoints/groups-endpoints/info

>> Retrieves the information about the private group, only if you're part of the group.

It seems even admin is not an exclusion. 

You already have some info at $goupesRocket, like the name of the group.

But it seems that you, as admin, can not do a lot with them via API. See these issues:
https://github.com/RocketChat/Rocket.Chat/issues/19658
https://github.com/RocketChat/Rocket.Chat/issues/22865

These are permission issues at Rocket Chat itself, not this package.
