### ISSUE TITLE
"error":"TOTP Required [totp-required]"

### ISSUE THREAD

**Issue by weeger** [alekseykuleshov/rocket-chat#16]
As seen in https://github.com/alekseykuleshov/rocket-chat/issues/8 we need to release some security restriction to be able to use "$user->update()" method.

It works but actually this is not a configuration issue, but new headers requirements as seen here : https://github.com/RocketChat/docs/pull/1799/commits/e79d3632120011c385f724bd964f633d89ebae05 

User API password should be now appended to request header for some operations, so I suggest this addition :  

```php
// In Request.php

    private static function getRequestOptions($method, $data, $files)
    {
        // ....

        if (!empty(self::$authToken)) {
            $headers["X-Auth-Token"] = self::$authToken;
        }
        
        // Adding encoded password...
        if (!empty(self::$authPassword)) {
            $headers["X-2fa-method"] = 'password';
            $headers["X-2fa-code"] = hash('sha256', self::$authPassword);
        }

**Comment by alekseykuleshov** [comment]
@weeger This change is added in the latest version. Thank you for your help and let me know if it works for you!
