### ISSUE TITLE
Doctrine/collections v2 required

### ISSUE THREAD

**Issue by kvelaro** [alekseykuleshov/rocket-chat#26]
Is there any development to this library?
    - atdev/rocket-chat[1.0.0, ..., 1.0.6] require doctrine/collections ~1.0 -> found doctrine/collections[v1.0, ..., 1.8.0] but the package is fixed to 2.1.2 (lock file version) by a partial update and that version does not match. Make sure you list it as an argument for the update command.

**Comment by alekseykuleshov** [comment]
@kvelaro I've updated doctrine/collections requirements.

**Comment by kvelaro** [comment]
Thank you
